# ã‚µã‚¤ãƒˆå…¨ä½“ã®åå‰
site_name: ãƒ¢ãƒ€ãƒ³Pythoné–‹ç™ºæ‰‹é †æ›¸

# ã‚µã‚¤ãƒˆã®ç›®æ¬¡ï¼ˆãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ï¼‰
nav:
  - 'ğŸ“œ ç§ãŸã¡ã®SOP': 'index.md'
  # - 'Chapter 1: åŸºæœ¬': 'c1/summary.md'   # â†å°†æ¥ã€C1ã®ã¾ã¨ã‚ã‚’ä½œã£ãŸã‚‰ã€ã“ã®ã‚³ãƒ¡ãƒ³ãƒˆã‚’å¤–ã™
  # - 'Chapter 2: ãƒ‡ãƒ¼ã‚¿æ§‹é€ ': 'c2/notes.md' # â†å°†æ¥ã€C2ã®ãƒãƒ¼ãƒˆã‚’ä½œã£ãŸã‚‰ã€ã“ã“ã‚’æœ‰åŠ¹ã«ã™ã‚‹
  # å°†æ¥ã€ãƒšãƒ¼ã‚¸ãŒå¢—ãˆãŸã‚‰ã€ã“ã“ã«è¿½åŠ ã—ã¦ã„ãã®ã‚ˆ

# ã‚µã‚¤ãƒˆã®è¦‹ãŸç›®ã‚’å¸ã‚‹ãƒ†ãƒ¼ãƒ
theme:
  name: material
  language: ja
  palette:
    scheme: slate   # ç¾ã—ã„ãƒ€ãƒ¼ã‚¯ãƒ¢ãƒ¼ãƒ‰
    primary: indigo # ã‚¢ã‚¯ã‚»ãƒ³ãƒˆã‚«ãƒ©ãƒ¼
  features:
    - navigation.tabs           # ä¸Šéƒ¨ã«ã‚¿ãƒ–ã‚’è¡¨ç¤º
    - navigation.instant        # ãƒšãƒ¼ã‚¸é·ç§»ã‚’é«˜é€ŸåŒ–
    - navigation.top            # ãƒˆãƒƒãƒ—ã¸æˆ»ã‚‹ãƒœã‚¿ãƒ³
    - toc.integrate             # å³å´ã«è¿½å¾“ã™ã‚‹ç›®æ¬¡
    - content.code.annotate     # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã«æ³¨é‡ˆã‚’è¿½åŠ ã§ãã‚‹

# Markdownã‚’æ‹¡å¼µã™ã‚‹é­”æ³•ã®å‘ªæ–‡
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true # å„è¦‹å‡ºã—ã«ãƒªãƒ³ã‚¯ã‚’ä»˜ã‘ã‚‹