site_name: ãƒ‘ãƒ¼ã‚½ãƒŠãƒ«SOPã‚µã‚¤ãƒˆ

nav:
  - 'ğŸ Python Basics':  # â†ã€é‡è¦ã€‘æ–°ã—ã„ã€å¤§ã‚«ãƒ†ã‚´ãƒªã‚’è¿½åŠ ï¼
      - 'æ§‹æ–‡ãƒãƒ¼ãƒˆã‚·ãƒ¼ãƒˆ': 'python_basics/01_syntax_cheatsheet.md'

  - '---': [] # â† ç¾ã—ã„ã€åŒºåˆ‡ã‚Šç·šã‚‚ã€å…¥ã‚Œã¦ãŠãã¾ã—ã‚‡ã†
  - 'VS Code': 'vscode.md'
  - 'Git': 'git.md'
  - 'ã‚³ãƒãƒ³ãƒ‰ãƒ»ãƒãƒ¼ãƒˆã‚·ãƒ¼ãƒˆ': 'commands.md'
  - 'MkDocs': 'mkdocs.md'
  - 'GitHub Pages': 'github_pages.md'
  - 'GitHub Actions': 'github_actions.md'

theme:
  name: material
  language: ja
  palette:
    scheme: slate